name: "Newman Tests"
on: [pull, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
     steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Run API Tests
      run: newman run "Resful Booker BVT.postman_collection.json" -e Production.postman_environment.json
